### ISSUE TITLE
Site Inspiration Collection

### ISSUE THREAD

**Issue by jaffrepaul** [NativeYogurt/ApplyMate#167]
Color Palette:
- Purple/blue/yellow https://jobtrack.io/users/sign_in
- Mint/Orange-ish (Light) http://bridge91.qodeinteractive.com/
- Mint/Orange-ish (Dark) http://websites.envatousercontent.com/designs/bridge-flat-company/130e5a27-d3d3-46d5-8d96-e8fd83d8d58b/preview
- Simple blue https://dribbble.com/shots/3893835-Landing-Page-Repair-Shop/attachments/885584

Helpful stuff:
- https://brandcolors.net/
- http://palettr.com/
- https://www.materialpalette.com/
- https://javier.xyz/cohesive-colors/

Site examples:
- https://dribbble.com/shots/3894818-Designers-Events-Dashboard
- https://www.awwwards.com/case-study-of-vr-arles-festival-website-by-les-animals.html

**Comment by bryangxyz** [comment]
i think that simple blue looks good.  another similar site. https://gojobhero.com/jobs/

**Comment by iamkennytso** [comment]
red/grey http://nytakeuchi.com/
dark bg/bright colors https://www.theverge.com/
modularized content https://pcpartpicker.com/
